### ISSUE TITLE
Unclear menu

### ISSUE THREAD

**Issue by kangaderoo** [ZeroPointThree17/radbag-wallet#2]
It took me some time to find out that the wallet-line and the adress-line on top were actual buttons.
A hamburger-icon just in front (and maybe a bigger font) might make this feature clear.
I realy like this feature to support multiple wallets in one app, a feature clearly missing in the desktop wallet.

**Comment by ZeroPointThree17** [comment]
Due to the component used for the dropdown, it was hard to put the hamburger icon without totally disrupting the rest of the layout. I have tried making the texts underlined, though, to make them seem more like links.  Take a look and let me know what you think.

![Simulator Screen Shot - iPhone 13 - 2022-04-12 at 10 19 20](https://user-images.githubusercontent.com/32686777/162997281-52d0ef39-dfd0-4cb6-9a99-91912e357f5b.png)
