### ISSUE TITLE
Support for encrypted messages

### ISSUE THREAD

**Issue by kangaderoo** [ZeroPointThree17/radbag-wallet#3]
I'd realy would be able to send/receive encrypted messages.

I did have a look into the code. But all requirements stopped me to make a clone for myself.
I did look into the code required for message encryption and found that not all functions are part of the crypto module.
So just in case you have not started this development yet, here is my NodeJS code with only the "crypto" requirement.
[RadixMessageCrypto.zip](https://github.com/ZeroPointThree17/radbag-wallet/files/8465769/RadixMessageCrypto.zip)
I've developed/tested this code on https://onecompiler.com/javascript.
There are a couple of ToDo's in the code that are security questions.
I also have no idea how to generate the diffie-hellman shared Point on the Curve using a hardware wallet.

**Comment by kangaderoo** [comment]
Hmm, I looked at the code I uploaded. 
The elliptic point multiplier might need to be rewritten to use Jacobian coordinates.
This will improve performance on the diffie-hellman Point calculation.

**Comment by ZeroPointThree17** [comment]
Thanks for sharing.  Certainly would be helpful to have when we start work on that.  The performance efficiency you mention would be nice to have as well.

Currently we are not prioritizing the encrypted message feature, because there are other features which might make more of an impact in the short term, and want to dedicate our time to those features. Certainly, once those other features are implemented, we can re-visit the encryption feature. I'll leave this issue open as a reminder. Feel free to implement your code into the RadBag codebase in the meantime if you are able, otherwise the RadBag team will attempt do so at a later point in time.

**Comment by kangaderoo** [comment]
I think I'll be working on the migration to the jacobian coordinate calculations, but I'll probably not be creating this developement environment for the complete project. I'll probably dumpt the code here again if/when completed.

**Comment by ZeroPointThree17** [comment]
Sounds good! Hoping such a code dump would help accelerate implementation.

**Comment by kangaderoo** [comment]
V2.13
